# Generated by Django 5.1.7 on 2025-03-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WebsiteInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("url", models.URLField(max_length=2000)),
                ("domain_name", models.CharField(max_length=255)),
                ("protocol", models.CharField(max_length=10)),
                ("title", models.TextField(blank=True, null=True)),
                ("images", models.JSONField(default=list)),
                ("stylesheets_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Website Information",
                "verbose_name_plural": "Website Information",
                "ordering": ["-created_at"],
            },
        ),
    ]
